### PR TITLE
Php5.5

### PR DESCRIPTION
**Pull request by sanpii**

### CODE REVIEW

**Comment by Halleck45** [comment]
Build fails :

>  ./bin/phpunit: No such file or directory

Why did you use the `bin-dir` directory ? I think that is better to have :
- `bin` : internal binaries
- `vendor/bin` (default) : external binaries (PHPUnit, etc. )

No ?

**Comment by sanpii** [comment]
I'm lazy to write `./vendor/bin` for each command, but it’s probably better…

I’ll fix this.

**Comment by Halleck45** [comment]
When you use only one `bin` directory, your dependencies (`bin/phpunit`, `bin/behat`, etc.) are commited... After a while it generates a lot of problems.

Thank's :)

**Comment by sanpii** [comment]
Amended :)

**Pull request merged**
